# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#authors"
  weight = 05

#[[main]]
  #name = "PsyPAG"
  #url = "psypag/"
  #weight = 30

[[main]]
 name = "RoSE Network"
 url = "rosenetwork/"
 weight = 25

[[main]]
 name = "Research"
 url = "research/"
 weight = 10

[[main]]
  name = "Posters"
  url = "posters/"
  weight = 15

[[main]]
  name = "Publications"
  url = "publications/"
  weight = 20

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.

[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 40

# [[main]]
 # name = "CV_old"
 # url = "cv_page/"
 # weight = 40

# [[main]]
  # name = "Blog"
  # url = "blog_page/"
  # weight = 45

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 50


